---
  - name: create directory ooffice
    file:
      path: /tmp/ooffice
      state: directory
      mode: '0755'

  - name: download ooffice
    get_url: 
      url: http://{{ repo_host }}/files/Apache_OpenOffice_{{ openoffice_version }}_Linux_x86-64_install-rpm_es.tar.gz 
      dest: /tmp/ooffice/Apache_OpenOffice.tar.gz 
    register: result
    until: result is success
    retries: 5
    delay: 10

  - name: unarchive ooffice
    unarchive: 
      src: /tmp/ooffice/Apache_OpenOffice.tar.gz
      dest: /tmp/ooffice
      remote_src: yes
    
  - name: install ooffice
    command: rpm -ivh *.rpm
    ignore_errors: yes
    args:
      chdir: /tmp/ooffice/es/RPMS/
      warn: false

  - name: remove ooffice RPM source packages
    file: 
      path: /tmp/ooffice/
      state: absent
 
