# This playbook changes wallpaper in KDE
- name: Descargar wallpaper
  get_url:
    url: http://{{ repo_host }}/files/2.png
    dest: /tmp/wall.png

- name: Cambiar Wallpaper 
  shell: export DISPLAY=:0
  shell: qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///tmp/wall.png")}' 

