# This playbook contains common plays that will be run on all nodes.
- name: Firewalld service state
  service: 
    name: firewalld 
    state: started 
    enabled: yes

- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing




